export const dashboardScript = `
const el=(id)=>document.getElementById(id);const token=el('token');token.value=sessionStorage.getItem('calliope_token')||'';
function headers(json=false){const h={};if(token.value)h.authorization='Bearer '+token.value;if(json)h['content-type']='application/json';return h}
async function api(path,options={}){const res=await fetch(path,{...options,headers:{...headers(options.body!==undefined),...(options.headers||{})}});const body=await res.json().catch(()=>({error:'invalid_json'}));if(!res.ok){const error=new Error(body.error||('HTTP '+res.status));error.status=res.status;throw error}return body}
function clear(node){while(node.firstChild)node.removeChild(node.firstChild)}function text(tag,value,cls){const n=document.createElement(tag);n.textContent=String(value);if(cls)n.className=cls;return n}
function empty(node){node.append(el('empty').content.cloneNode(true))}function table(headers,rows){const t=document.createElement('table'),head=document.createElement('tr');headers.forEach(h=>head.append(text('th',h)));const th=document.createElement('thead');th.append(head);t.append(th);const tb=document.createElement('tbody');rows.forEach(row=>{const tr=document.createElement('tr');row.forEach(value=>tr.append(text('td',value??'—')));tb.append(tr)});t.append(tb);return t}
function renderSummary(data){const node=el('summary');clear(node);[['Plan tasks',data.plan?.entries?.length||0],['Active sprints',data.sprints.length],['Decisions',data.decisions.length],['Alerts',data.briefing.summary.alerts]].forEach(([label,value])=>{const c=text('div','', 'panel card');c.append(text('strong',value));c.append(text('span',label));node.append(c)})}
function renderPlan(plan){const node=el('plan');clear(node);if(!plan){empty(node);return}node.append(text('p',plan.id,'muted'));node.append(table(['Lane','Task ref','Start','End'],plan.entries.map(e=>[e.lane,e.taskRef,e.startAt,e.endAt])))}
function renderSprints(items){const node=el('sprints');clear(node);if(!items.length){empty(node);return}node.append(table(['Project','Status','Period end','Target'],items.map(s=>[s.projectRef,s.status,s.periodEnd,s.targetVelocity])))}
function renderVelocity(items){const node=el('velocity');clear(node);if(!items.length){empty(node);return}node.append(table(['Project','Category','k-factor','Throughput','Samples'],items.map(v=>[v.projectRef,v.category,v.kFactor.toFixed(2),v.throughput.toFixed(1),v.sampleSize])))}
function renderDecisions(items){const node=el('decisions');clear(node);if(!items.length){empty(node);return}items.forEach(d=>{const box=text('div','', 'item');box.append(text('span',d.kind,'badge '+(d.kind==='calendar_write'?'amber':'')));box.append(text('p',d.id,'muted'));box.append(text('p','expires '+d.expiresAt,'muted'));const actions=text('div','', 'decision-actions');const approve=text('button','Approve');approve.onclick=()=>decide(d.id,'approve');const reject=text('button','Reject');reject.onclick=()=>decide(d.id,'reject');actions.append(approve,reject);box.append(actions);node.append(box)})}
function renderRetro(r){const node=el('retrospective');clear(node);node.append(text('p',r.weekStart.slice(0,10)+' → '+r.weekEnd.slice(0,10),'muted'));node.append(table(['Metric','Value'],[['Velocity series',r.velocityDrift.length],['Scope creep',(r.scopeCreep.averageRate*100).toFixed(1)+'%'],['Aging activations',r.starvation.length],['Reschedules',r.reschedules.total]]));r.recommendations.forEach(rec=>{const p=text('p',rec.message,'item');node.append(p)})}
async function decide(id,decision){try{const body=decision==='reject'?{decision,reason:'Rejected from dashboard'}:{decision};await api('/api/confirmations/'+encodeURIComponent(id),{method:'POST',body:JSON.stringify(body)});await load()}catch(e){showError(e)}}
function showError(e){el('status').textContent=e instanceof Error?e.message:String(e);el('status').className='error'}
async function load(){el('status').textContent='更新中';el('status').className='';try{const [plans,sprints,velocity,decisions,briefing,retro]=await Promise.all([api('/api/plan?status=active'),api('/api/sprint'),api('/api/velocity'),api('/api/confirmations?status=pending'),api('/api/briefing/today'),api('/api/retrospective/weekly')]);const active=plans.plans[0];const plan=active?(await api('/api/plan/'+encodeURIComponent(active.id))).plan:null;const data={plan,sprints:sprints.sprints,velocity:velocity.rows,decisions:decisions.confirmations,briefing,retro};renderSummary(data);renderPlan(plan);renderSprints(data.sprints);renderVelocity(data.velocity);renderDecisions(data.decisions);renderRetro(retro);el('status').textContent='接続済み'}catch(e){showError(e)}}
el('save-token').onclick=()=>{sessionStorage.setItem('calliope_token',token.value);load()};el('refresh').onclick=load;
el('simulate').onclick=async()=>{try{const result=await api('/api/plan/simulate',{method:'POST',body:JSON.stringify({changes:{lanes:Number(el('lanes').value)}})});el('simulation').textContent=JSON.stringify(result,null,2)}catch(e){showError(e)}};
el('reschedule').onclick=async()=>{try{await api('/api/reschedule/trigger',{method:'POST',body:JSON.stringify({trigger:'manual'})});await load()}catch(e){if(e&&e.status===409)await load();else showError(e)}};
el('calendar-sync').onclick=async()=>{try{await api('/api/calendar/sync',{method:'POST',body:'{}'});await load()}catch(e){if(e&&e.status===409)await load();else showError(e)}};
el('send-weekly').onclick=async()=>{try{await api('/api/retrospective/weekly/send',{method:'POST',body:'{}'});el('status').textContent='週次レポート送信完了'}catch(e){showError(e)}};
if(token.value)load();
`;
